branch-defaults:
  master:
    environment: eb-deploy-base-master
environment-defaults:
  eb-deploy-base:
    branch: null
    repository: null
global:
  application_name: eb-deploy-base
  default_ec2_keyname: eb-deploy-base
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Docker running
    on 64bit Amazon Linux/2.12.14
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-deploy-base
  sc: git
  workspace_type: Application
